


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mdscore"
version = "0.1"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mdscore*"]

